# Enable USART1
CONFIG_SERIAL=y

# Enable GPIO
CONFIG_GPIO=y

# Enable printk for debugging
CONFIG_PRINTK=y
CONFIG_LOG=y

# Enable necessary drivers
CONFIG_GPIO_STM32=y
CONFIG_UART_STM32=y

# Set printk to output on USART1
# CONFIG_UART_CONSOLE_ON_DEVICE=y
# CONFIG_UART_CONSOLE_DEVICE_NAME="USART_1"